name: Zip and Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove unwanted files
        run: |
          chmod 777 ./remove.sh
          ./remove.sh
      - name: Zip the files
        run: |
          cd ..
          mv WordPress-Plugin push-notifications-by-larapush
          zip -r push-notifications-by-larapush.zip push-notifications-by-larapush/*
          mv push-notifications-by-larapush WordPress-Plugin
          mv push-notifications-by-larapush.zip WordPress-Plugin/
      - name: Uploading Files to Server
        run: |
          sshpass -p '${{ secrets.FTP_SERVER_PASSWORD }}' scp -o StrictHostKeyChecking=no push-notifications-by-larapush.zip ${{ secrets.FTP_SERVER_USER }}@${{ secrets.FTP_SERVER_IP }}:${{ secrets.FTP_SERVER_PATH }}
